// flow-typed signature: 7eb31a5a6720f9fa4e9d8a7340b4fb5e
// flow-typed version: <<STUB>>/found_v1.3.0/flow_v0.231.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'found'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'found' {
  declare module.exports: any;
}

declare module 'found/Link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'found/cjs/ActionTypes' {
  declare module.exports: any;
}

declare module 'found/cjs/createBaseRouter' {
  declare module.exports: any;
}

declare module 'found/cjs/createBrowserRouter' {
  declare module.exports: any;
}

declare module 'found/cjs/createConnectedRouter' {
  declare module.exports: any;
}

declare module 'found/cjs/createElements' {
  declare module.exports: any;
}

declare module 'found/cjs/createFarceRouter' {
  declare module.exports: any;
}

declare module 'found/cjs/createFarceStore' {
  declare module.exports: any;
}

declare module 'found/cjs/createInitialBrowserRouter' {
  declare module.exports: any;
}

declare module 'found/cjs/createInitialFarceRouter' {
  declare module.exports: any;
}

declare module 'found/cjs/createMatchEnhancer' {
  declare module.exports: any;
}

declare module 'found/cjs/createRender' {
  declare module.exports: any;
}

declare module 'found/cjs/createStoreRouterObject' {
  declare module.exports: any;
}

declare module 'found/cjs/ElementsRenderer' {
  declare module.exports: any;
}

declare module 'found/cjs/foundReducer' {
  declare module.exports: any;
}

declare module 'found/cjs/getRenderArgs' {
  declare module.exports: any;
}

declare module 'found/cjs/getStoreRenderArgs' {
  declare module.exports: any;
}

declare module 'found/cjs/hotRouteConfig' {
  declare module.exports: any;
}

declare module 'found/cjs/HttpError' {
  declare module.exports: any;
}

declare module 'found/cjs' {
  declare module.exports: any;
}

declare module 'found/cjs/Link' {
  declare module.exports: any;
}

declare module 'found/cjs/makeRouteConfig' {
  declare module.exports: any;
}

declare module 'found/cjs/Matcher' {
  declare module.exports: any;
}

declare module 'found/cjs/pathToRegexp' {
  declare module.exports: any;
}

declare module 'found/cjs/Redirect' {
  declare module.exports: any;
}

declare module 'found/cjs/RedirectException' {
  declare module.exports: any;
}

declare module 'found/cjs/resolver' {
  declare module.exports: any;
}

declare module 'found/cjs/resolveRenderArgs' {
  declare module.exports: any;
}

declare module 'found/cjs/ResolverUtils' {
  declare module.exports: any;
}

declare module 'found/cjs/Route' {
  declare module.exports: any;
}

declare module 'found/cjs/RouterContext' {
  declare module.exports: any;
}

declare module 'found/cjs/server' {
  declare module.exports: any;
}

declare module 'found/cjs/StaticContainer' {
  declare module.exports: any;
}

declare module 'found/cjs/typeUtils' {
  declare module.exports: any;
}

declare module 'found/cjs/useLocation' {
  declare module.exports: any;
}

declare module 'found/cjs/useMatch' {
  declare module.exports: any;
}

declare module 'found/cjs/useParams' {
  declare module.exports: any;
}

declare module 'found/cjs/useRouter' {
  declare module.exports: any;
}

declare module 'found/cjs/withRouter' {
  declare module.exports: any;
}

declare module 'found/esm/ActionTypes' {
  declare module.exports: any;
}

declare module 'found/esm/createBaseRouter' {
  declare module.exports: any;
}

declare module 'found/esm/createBrowserRouter' {
  declare module.exports: any;
}

declare module 'found/esm/createConnectedRouter' {
  declare module.exports: any;
}

declare module 'found/esm/createElements' {
  declare module.exports: any;
}

declare module 'found/esm/createFarceRouter' {
  declare module.exports: any;
}

declare module 'found/esm/createFarceStore' {
  declare module.exports: any;
}

declare module 'found/esm/createInitialBrowserRouter' {
  declare module.exports: any;
}

declare module 'found/esm/createInitialFarceRouter' {
  declare module.exports: any;
}

declare module 'found/esm/createMatchEnhancer' {
  declare module.exports: any;
}

declare module 'found/esm/createRender' {
  declare module.exports: any;
}

declare module 'found/esm/createStoreRouterObject' {
  declare module.exports: any;
}

declare module 'found/esm/ElementsRenderer' {
  declare module.exports: any;
}

declare module 'found/esm/foundReducer' {
  declare module.exports: any;
}

declare module 'found/esm/getRenderArgs' {
  declare module.exports: any;
}

declare module 'found/esm/getStoreRenderArgs' {
  declare module.exports: any;
}

declare module 'found/esm/hotRouteConfig' {
  declare module.exports: any;
}

declare module 'found/esm/HttpError' {
  declare module.exports: any;
}

declare module 'found/esm' {
  declare module.exports: any;
}

declare module 'found/esm/Link' {
  declare module.exports: any;
}

declare module 'found/esm/makeRouteConfig' {
  declare module.exports: any;
}

declare module 'found/esm/Matcher' {
  declare module.exports: any;
}

declare module 'found/esm/pathToRegexp' {
  declare module.exports: any;
}

declare module 'found/esm/Redirect' {
  declare module.exports: any;
}

declare module 'found/esm/RedirectException' {
  declare module.exports: any;
}

declare module 'found/esm/resolver' {
  declare module.exports: any;
}

declare module 'found/esm/resolveRenderArgs' {
  declare module.exports: any;
}

declare module 'found/esm/ResolverUtils' {
  declare module.exports: any;
}

declare module 'found/esm/Route' {
  declare module.exports: any;
}

declare module 'found/esm/RouterContext' {
  declare module.exports: any;
}

declare module 'found/esm/server' {
  declare module.exports: any;
}

declare module 'found/esm/StaticContainer' {
  declare module.exports: any;
}

declare module 'found/esm/typeUtils' {
  declare module.exports: any;
}

declare module 'found/esm/useLocation' {
  declare module.exports: any;
}

declare module 'found/esm/useMatch' {
  declare module.exports: any;
}

declare module 'found/esm/useParams' {
  declare module.exports: any;
}

declare module 'found/esm/useRouter' {
  declare module.exports: any;
}

declare module 'found/esm/withRouter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'found/cjs/ActionTypes.js' {
  declare module.exports: $Exports<'found/cjs/ActionTypes'>;
}
declare module 'found/cjs/createBaseRouter.js' {
  declare module.exports: $Exports<'found/cjs/createBaseRouter'>;
}
declare module 'found/cjs/createBrowserRouter.js' {
  declare module.exports: $Exports<'found/cjs/createBrowserRouter'>;
}
declare module 'found/cjs/createConnectedRouter.js' {
  declare module.exports: $Exports<'found/cjs/createConnectedRouter'>;
}
declare module 'found/cjs/createElements.js' {
  declare module.exports: $Exports<'found/cjs/createElements'>;
}
declare module 'found/cjs/createFarceRouter.js' {
  declare module.exports: $Exports<'found/cjs/createFarceRouter'>;
}
declare module 'found/cjs/createFarceStore.js' {
  declare module.exports: $Exports<'found/cjs/createFarceStore'>;
}
declare module 'found/cjs/createInitialBrowserRouter.js' {
  declare module.exports: $Exports<'found/cjs/createInitialBrowserRouter'>;
}
declare module 'found/cjs/createInitialFarceRouter.js' {
  declare module.exports: $Exports<'found/cjs/createInitialFarceRouter'>;
}
declare module 'found/cjs/createMatchEnhancer.js' {
  declare module.exports: $Exports<'found/cjs/createMatchEnhancer'>;
}
declare module 'found/cjs/createRender.js' {
  declare module.exports: $Exports<'found/cjs/createRender'>;
}
declare module 'found/cjs/createStoreRouterObject.js' {
  declare module.exports: $Exports<'found/cjs/createStoreRouterObject'>;
}
declare module 'found/cjs/ElementsRenderer.js' {
  declare module.exports: $Exports<'found/cjs/ElementsRenderer'>;
}
declare module 'found/cjs/foundReducer.js' {
  declare module.exports: $Exports<'found/cjs/foundReducer'>;
}
declare module 'found/cjs/getRenderArgs.js' {
  declare module.exports: $Exports<'found/cjs/getRenderArgs'>;
}
declare module 'found/cjs/getStoreRenderArgs.js' {
  declare module.exports: $Exports<'found/cjs/getStoreRenderArgs'>;
}
declare module 'found/cjs/hotRouteConfig.js' {
  declare module.exports: $Exports<'found/cjs/hotRouteConfig'>;
}
declare module 'found/cjs/HttpError.js' {
  declare module.exports: $Exports<'found/cjs/HttpError'>;
}
declare module 'found/cjs/index' {
  declare module.exports: $Exports<'found/cjs'>;
}
declare module 'found/cjs/index.js' {
  declare module.exports: $Exports<'found/cjs'>;
}
declare module 'found/cjs/Link.js' {
  declare module.exports: $Exports<'found/cjs/Link'>;
}
declare module 'found/cjs/makeRouteConfig.js' {
  declare module.exports: $Exports<'found/cjs/makeRouteConfig'>;
}
declare module 'found/cjs/Matcher.js' {
  declare module.exports: $Exports<'found/cjs/Matcher'>;
}
declare module 'found/cjs/pathToRegexp.js' {
  declare module.exports: $Exports<'found/cjs/pathToRegexp'>;
}
declare module 'found/cjs/Redirect.js' {
  declare module.exports: $Exports<'found/cjs/Redirect'>;
}
declare module 'found/cjs/RedirectException.js' {
  declare module.exports: $Exports<'found/cjs/RedirectException'>;
}
declare module 'found/cjs/resolver.js' {
  declare module.exports: $Exports<'found/cjs/resolver'>;
}
declare module 'found/cjs/resolveRenderArgs.js' {
  declare module.exports: $Exports<'found/cjs/resolveRenderArgs'>;
}
declare module 'found/cjs/ResolverUtils.js' {
  declare module.exports: $Exports<'found/cjs/ResolverUtils'>;
}
declare module 'found/cjs/Route.js' {
  declare module.exports: $Exports<'found/cjs/Route'>;
}
declare module 'found/cjs/RouterContext.js' {
  declare module.exports: $Exports<'found/cjs/RouterContext'>;
}
declare module 'found/cjs/server.js' {
  declare module.exports: $Exports<'found/cjs/server'>;
}
declare module 'found/cjs/StaticContainer.js' {
  declare module.exports: $Exports<'found/cjs/StaticContainer'>;
}
declare module 'found/cjs/typeUtils.js' {
  declare module.exports: $Exports<'found/cjs/typeUtils'>;
}
declare module 'found/cjs/useLocation.js' {
  declare module.exports: $Exports<'found/cjs/useLocation'>;
}
declare module 'found/cjs/useMatch.js' {
  declare module.exports: $Exports<'found/cjs/useMatch'>;
}
declare module 'found/cjs/useParams.js' {
  declare module.exports: $Exports<'found/cjs/useParams'>;
}
declare module 'found/cjs/useRouter.js' {
  declare module.exports: $Exports<'found/cjs/useRouter'>;
}
declare module 'found/cjs/withRouter.js' {
  declare module.exports: $Exports<'found/cjs/withRouter'>;
}
declare module 'found/esm/ActionTypes.js' {
  declare module.exports: $Exports<'found/esm/ActionTypes'>;
}
declare module 'found/esm/createBaseRouter.js' {
  declare module.exports: $Exports<'found/esm/createBaseRouter'>;
}
declare module 'found/esm/createBrowserRouter.js' {
  declare module.exports: $Exports<'found/esm/createBrowserRouter'>;
}
declare module 'found/esm/createConnectedRouter.js' {
  declare module.exports: $Exports<'found/esm/createConnectedRouter'>;
}
declare module 'found/esm/createElements.js' {
  declare module.exports: $Exports<'found/esm/createElements'>;
}
declare module 'found/esm/createFarceRouter.js' {
  declare module.exports: $Exports<'found/esm/createFarceRouter'>;
}
declare module 'found/esm/createFarceStore.js' {
  declare module.exports: $Exports<'found/esm/createFarceStore'>;
}
declare module 'found/esm/createInitialBrowserRouter.js' {
  declare module.exports: $Exports<'found/esm/createInitialBrowserRouter'>;
}
declare module 'found/esm/createInitialFarceRouter.js' {
  declare module.exports: $Exports<'found/esm/createInitialFarceRouter'>;
}
declare module 'found/esm/createMatchEnhancer.js' {
  declare module.exports: $Exports<'found/esm/createMatchEnhancer'>;
}
declare module 'found/esm/createRender.js' {
  declare module.exports: $Exports<'found/esm/createRender'>;
}
declare module 'found/esm/createStoreRouterObject.js' {
  declare module.exports: $Exports<'found/esm/createStoreRouterObject'>;
}
declare module 'found/esm/ElementsRenderer.js' {
  declare module.exports: $Exports<'found/esm/ElementsRenderer'>;
}
declare module 'found/esm/foundReducer.js' {
  declare module.exports: $Exports<'found/esm/foundReducer'>;
}
declare module 'found/esm/getRenderArgs.js' {
  declare module.exports: $Exports<'found/esm/getRenderArgs'>;
}
declare module 'found/esm/getStoreRenderArgs.js' {
  declare module.exports: $Exports<'found/esm/getStoreRenderArgs'>;
}
declare module 'found/esm/hotRouteConfig.js' {
  declare module.exports: $Exports<'found/esm/hotRouteConfig'>;
}
declare module 'found/esm/HttpError.js' {
  declare module.exports: $Exports<'found/esm/HttpError'>;
}
declare module 'found/esm/index' {
  declare module.exports: $Exports<'found/esm'>;
}
declare module 'found/esm/index.js' {
  declare module.exports: $Exports<'found/esm'>;
}
declare module 'found/esm/Link.js' {
  declare module.exports: $Exports<'found/esm/Link'>;
}
declare module 'found/esm/makeRouteConfig.js' {
  declare module.exports: $Exports<'found/esm/makeRouteConfig'>;
}
declare module 'found/esm/Matcher.js' {
  declare module.exports: $Exports<'found/esm/Matcher'>;
}
declare module 'found/esm/pathToRegexp.js' {
  declare module.exports: $Exports<'found/esm/pathToRegexp'>;
}
declare module 'found/esm/Redirect.js' {
  declare module.exports: $Exports<'found/esm/Redirect'>;
}
declare module 'found/esm/RedirectException.js' {
  declare module.exports: $Exports<'found/esm/RedirectException'>;
}
declare module 'found/esm/resolver.js' {
  declare module.exports: $Exports<'found/esm/resolver'>;
}
declare module 'found/esm/resolveRenderArgs.js' {
  declare module.exports: $Exports<'found/esm/resolveRenderArgs'>;
}
declare module 'found/esm/ResolverUtils.js' {
  declare module.exports: $Exports<'found/esm/ResolverUtils'>;
}
declare module 'found/esm/Route.js' {
  declare module.exports: $Exports<'found/esm/Route'>;
}
declare module 'found/esm/RouterContext.js' {
  declare module.exports: $Exports<'found/esm/RouterContext'>;
}
declare module 'found/esm/server.js' {
  declare module.exports: $Exports<'found/esm/server'>;
}
declare module 'found/esm/StaticContainer.js' {
  declare module.exports: $Exports<'found/esm/StaticContainer'>;
}
declare module 'found/esm/typeUtils.js' {
  declare module.exports: $Exports<'found/esm/typeUtils'>;
}
declare module 'found/esm/useLocation.js' {
  declare module.exports: $Exports<'found/esm/useLocation'>;
}
declare module 'found/esm/useMatch.js' {
  declare module.exports: $Exports<'found/esm/useMatch'>;
}
declare module 'found/esm/useParams.js' {
  declare module.exports: $Exports<'found/esm/useParams'>;
}
declare module 'found/esm/useRouter.js' {
  declare module.exports: $Exports<'found/esm/useRouter'>;
}
declare module 'found/esm/withRouter.js' {
  declare module.exports: $Exports<'found/esm/withRouter'>;
}
