// flow-typed signature: d12413dfe03e1e8e75e1f0202589770c
// flow-typed version: <<STUB>>/react-use_v17.6.0/flow_v0.231.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-use'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-use' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-use/esm/component/UseKey' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createBreakpoint' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createGlobalState' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createHTMLMediaHook' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createMemo' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createReducer' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createReducerContext' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createRenderProp' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createRouter' {
  declare module.exports: any;
}

declare module 'react-use/esm/factory/createStateContext' {
  declare module.exports: any;
}

declare module 'react-use/esm' {
  declare module.exports: any;
}

declare module 'react-use/esm/misc/hookState' {
  declare module.exports: any;
}

declare module 'react-use/esm/misc/isDeepEqual' {
  declare module.exports: any;
}

declare module 'react-use/esm/misc/parseTimeRanges' {
  declare module.exports: any;
}

declare module 'react-use/esm/misc/types' {
  declare module.exports: any;
}

declare module 'react-use/esm/misc/util' {
  declare module.exports: any;
}

declare module 'react-use/esm/useAsync' {
  declare module.exports: any;
}

declare module 'react-use/esm/useAsyncFn' {
  declare module.exports: any;
}

declare module 'react-use/esm/useAsyncRetry' {
  declare module.exports: any;
}

declare module 'react-use/esm/useAudio' {
  declare module.exports: any;
}

declare module 'react-use/esm/useBattery' {
  declare module.exports: any;
}

declare module 'react-use/esm/useBeforeUnload' {
  declare module.exports: any;
}

declare module 'react-use/esm/useBoolean' {
  declare module.exports: any;
}

declare module 'react-use/esm/useClickAway' {
  declare module.exports: any;
}

declare module 'react-use/esm/useCookie' {
  declare module.exports: any;
}

declare module 'react-use/esm/useCopyToClipboard' {
  declare module.exports: any;
}

declare module 'react-use/esm/useCounter' {
  declare module.exports: any;
}

declare module 'react-use/esm/useCss' {
  declare module.exports: any;
}

declare module 'react-use/esm/useCustomCompareEffect' {
  declare module.exports: any;
}

declare module 'react-use/esm/useDebounce' {
  declare module.exports: any;
}

declare module 'react-use/esm/useDeepCompareEffect' {
  declare module.exports: any;
}

declare module 'react-use/esm/useDefault' {
  declare module.exports: any;
}

declare module 'react-use/esm/useDrop' {
  declare module.exports: any;
}

declare module 'react-use/esm/useDropArea' {
  declare module.exports: any;
}

declare module 'react-use/esm/useEffectOnce' {
  declare module.exports: any;
}

declare module 'react-use/esm/useEnsuredForwardedRef' {
  declare module.exports: any;
}

declare module 'react-use/esm/useError' {
  declare module.exports: any;
}

declare module 'react-use/esm/useEvent' {
  declare module.exports: any;
}

declare module 'react-use/esm/useFavicon' {
  declare module.exports: any;
}

declare module 'react-use/esm/useFirstMountState' {
  declare module.exports: any;
}

declare module 'react-use/esm/useFullscreen' {
  declare module.exports: any;
}

declare module 'react-use/esm/useGeolocation' {
  declare module.exports: any;
}

declare module 'react-use/esm/useGetSet' {
  declare module.exports: any;
}

declare module 'react-use/esm/useGetSetState' {
  declare module.exports: any;
}

declare module 'react-use/esm/useHarmonicIntervalFn' {
  declare module.exports: any;
}

declare module 'react-use/esm/useHash' {
  declare module.exports: any;
}

declare module 'react-use/esm/useHover' {
  declare module.exports: any;
}

declare module 'react-use/esm/useHoverDirty' {
  declare module.exports: any;
}

declare module 'react-use/esm/useIdle' {
  declare module.exports: any;
}

declare module 'react-use/esm/useIntersection' {
  declare module.exports: any;
}

declare module 'react-use/esm/useInterval' {
  declare module.exports: any;
}

declare module 'react-use/esm/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-use/esm/useKey' {
  declare module.exports: any;
}

declare module 'react-use/esm/useKeyboardJs' {
  declare module.exports: any;
}

declare module 'react-use/esm/useKeyPress' {
  declare module.exports: any;
}

declare module 'react-use/esm/useKeyPressEvent' {
  declare module.exports: any;
}

declare module 'react-use/esm/useLatest' {
  declare module.exports: any;
}

declare module 'react-use/esm/useLifecycles' {
  declare module.exports: any;
}

declare module 'react-use/esm/useList' {
  declare module.exports: any;
}

declare module 'react-use/esm/useLocalStorage' {
  declare module.exports: any;
}

declare module 'react-use/esm/useLocation' {
  declare module.exports: any;
}

declare module 'react-use/esm/useLockBodyScroll' {
  declare module.exports: any;
}

declare module 'react-use/esm/useLogger' {
  declare module.exports: any;
}

declare module 'react-use/esm/useLongPress' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMap' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMeasure' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMeasureDirty' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMedia' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMediaDevices' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMediatedState' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMethods' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMotion' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMount' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMountedState' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMouse' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMouseHovered' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMouseWheel' {
  declare module.exports: any;
}

declare module 'react-use/esm/useMultiStateValidator' {
  declare module.exports: any;
}

declare module 'react-use/esm/useNetworkState' {
  declare module.exports: any;
}

declare module 'react-use/esm/useNumber' {
  declare module.exports: any;
}

declare module 'react-use/esm/useObservable' {
  declare module.exports: any;
}

declare module 'react-use/esm/useOrientation' {
  declare module.exports: any;
}

declare module 'react-use/esm/usePageLeave' {
  declare module.exports: any;
}

declare module 'react-use/esm/usePermission' {
  declare module.exports: any;
}

declare module 'react-use/esm/usePinchZoom' {
  declare module.exports: any;
}

declare module 'react-use/esm/usePrevious' {
  declare module.exports: any;
}

declare module 'react-use/esm/usePreviousDistinct' {
  declare module.exports: any;
}

declare module 'react-use/esm/usePromise' {
  declare module.exports: any;
}

declare module 'react-use/esm/useQueue' {
  declare module.exports: any;
}

declare module 'react-use/esm/useRaf' {
  declare module.exports: any;
}

declare module 'react-use/esm/useRafLoop' {
  declare module.exports: any;
}

declare module 'react-use/esm/useRafState' {
  declare module.exports: any;
}

declare module 'react-use/esm/useRendersCount' {
  declare module.exports: any;
}

declare module 'react-use/esm/useScratch' {
  declare module.exports: any;
}

declare module 'react-use/esm/useScroll' {
  declare module.exports: any;
}

declare module 'react-use/esm/useScrollbarWidth' {
  declare module.exports: any;
}

declare module 'react-use/esm/useScrolling' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSearchParam' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSessionStorage' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSet' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSetState' {
  declare module.exports: any;
}

declare module 'react-use/esm/useShallowCompareEffect' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSize' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSlider' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSpeech' {
  declare module.exports: any;
}

declare module 'react-use/esm/useSpring' {
  declare module.exports: any;
}

declare module 'react-use/esm/useStartTyping' {
  declare module.exports: any;
}

declare module 'react-use/esm/useStateList' {
  declare module.exports: any;
}

declare module 'react-use/esm/useStateValidator' {
  declare module.exports: any;
}

declare module 'react-use/esm/useStateWithHistory' {
  declare module.exports: any;
}

declare module 'react-use/esm/useThrottle' {
  declare module.exports: any;
}

declare module 'react-use/esm/useThrottleFn' {
  declare module.exports: any;
}

declare module 'react-use/esm/useTimeout' {
  declare module.exports: any;
}

declare module 'react-use/esm/useTimeoutFn' {
  declare module.exports: any;
}

declare module 'react-use/esm/useTitle' {
  declare module.exports: any;
}

declare module 'react-use/esm/useToggle' {
  declare module.exports: any;
}

declare module 'react-use/esm/useTween' {
  declare module.exports: any;
}

declare module 'react-use/esm/useUnmount' {
  declare module.exports: any;
}

declare module 'react-use/esm/useUnmountPromise' {
  declare module.exports: any;
}

declare module 'react-use/esm/useUpdate' {
  declare module.exports: any;
}

declare module 'react-use/esm/useUpdateEffect' {
  declare module.exports: any;
}

declare module 'react-use/esm/useUpsert' {
  declare module.exports: any;
}

declare module 'react-use/esm/useVibrate' {
  declare module.exports: any;
}

declare module 'react-use/esm/useVideo' {
  declare module.exports: any;
}

declare module 'react-use/esm/useWait' {
  declare module.exports: any;
}

declare module 'react-use/esm/useWindowScroll' {
  declare module.exports: any;
}

declare module 'react-use/esm/useWindowSize' {
  declare module.exports: any;
}

declare module 'react-use/lib/component/UseKey' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createBreakpoint' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createGlobalState' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createHTMLMediaHook' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createMemo' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createReducer' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createReducerContext' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createRenderProp' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createRouter' {
  declare module.exports: any;
}

declare module 'react-use/lib/factory/createStateContext' {
  declare module.exports: any;
}

declare module 'react-use/lib' {
  declare module.exports: any;
}

declare module 'react-use/lib/misc/hookState' {
  declare module.exports: any;
}

declare module 'react-use/lib/misc/isDeepEqual' {
  declare module.exports: any;
}

declare module 'react-use/lib/misc/parseTimeRanges' {
  declare module.exports: any;
}

declare module 'react-use/lib/misc/types' {
  declare module.exports: any;
}

declare module 'react-use/lib/misc/util' {
  declare module.exports: any;
}

declare module 'react-use/lib/useAsync' {
  declare module.exports: any;
}

declare module 'react-use/lib/useAsyncFn' {
  declare module.exports: any;
}

declare module 'react-use/lib/useAsyncRetry' {
  declare module.exports: any;
}

declare module 'react-use/lib/useAudio' {
  declare module.exports: any;
}

declare module 'react-use/lib/useBattery' {
  declare module.exports: any;
}

declare module 'react-use/lib/useBeforeUnload' {
  declare module.exports: any;
}

declare module 'react-use/lib/useBoolean' {
  declare module.exports: any;
}

declare module 'react-use/lib/useClickAway' {
  declare module.exports: any;
}

declare module 'react-use/lib/useCookie' {
  declare module.exports: any;
}

declare module 'react-use/lib/useCopyToClipboard' {
  declare module.exports: any;
}

declare module 'react-use/lib/useCounter' {
  declare module.exports: any;
}

declare module 'react-use/lib/useCss' {
  declare module.exports: any;
}

declare module 'react-use/lib/useCustomCompareEffect' {
  declare module.exports: any;
}

declare module 'react-use/lib/useDebounce' {
  declare module.exports: any;
}

declare module 'react-use/lib/useDeepCompareEffect' {
  declare module.exports: any;
}

declare module 'react-use/lib/useDefault' {
  declare module.exports: any;
}

declare module 'react-use/lib/useDrop' {
  declare module.exports: any;
}

declare module 'react-use/lib/useDropArea' {
  declare module.exports: any;
}

declare module 'react-use/lib/useEffectOnce' {
  declare module.exports: any;
}

declare module 'react-use/lib/useEnsuredForwardedRef' {
  declare module.exports: any;
}

declare module 'react-use/lib/useError' {
  declare module.exports: any;
}

declare module 'react-use/lib/useEvent' {
  declare module.exports: any;
}

declare module 'react-use/lib/useFavicon' {
  declare module.exports: any;
}

declare module 'react-use/lib/useFirstMountState' {
  declare module.exports: any;
}

declare module 'react-use/lib/useFullscreen' {
  declare module.exports: any;
}

declare module 'react-use/lib/useGeolocation' {
  declare module.exports: any;
}

declare module 'react-use/lib/useGetSet' {
  declare module.exports: any;
}

declare module 'react-use/lib/useGetSetState' {
  declare module.exports: any;
}

declare module 'react-use/lib/useHarmonicIntervalFn' {
  declare module.exports: any;
}

declare module 'react-use/lib/useHash' {
  declare module.exports: any;
}

declare module 'react-use/lib/useHover' {
  declare module.exports: any;
}

declare module 'react-use/lib/useHoverDirty' {
  declare module.exports: any;
}

declare module 'react-use/lib/useIdle' {
  declare module.exports: any;
}

declare module 'react-use/lib/useIntersection' {
  declare module.exports: any;
}

declare module 'react-use/lib/useInterval' {
  declare module.exports: any;
}

declare module 'react-use/lib/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-use/lib/useKey' {
  declare module.exports: any;
}

declare module 'react-use/lib/useKeyboardJs' {
  declare module.exports: any;
}

declare module 'react-use/lib/useKeyPress' {
  declare module.exports: any;
}

declare module 'react-use/lib/useKeyPressEvent' {
  declare module.exports: any;
}

declare module 'react-use/lib/useLatest' {
  declare module.exports: any;
}

declare module 'react-use/lib/useLifecycles' {
  declare module.exports: any;
}

declare module 'react-use/lib/useList' {
  declare module.exports: any;
}

declare module 'react-use/lib/useLocalStorage' {
  declare module.exports: any;
}

declare module 'react-use/lib/useLocation' {
  declare module.exports: any;
}

declare module 'react-use/lib/useLockBodyScroll' {
  declare module.exports: any;
}

declare module 'react-use/lib/useLogger' {
  declare module.exports: any;
}

declare module 'react-use/lib/useLongPress' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMap' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMeasure' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMeasureDirty' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMedia' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMediaDevices' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMediatedState' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMethods' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMotion' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMount' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMountedState' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMouse' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMouseHovered' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMouseWheel' {
  declare module.exports: any;
}

declare module 'react-use/lib/useMultiStateValidator' {
  declare module.exports: any;
}

declare module 'react-use/lib/useNetworkState' {
  declare module.exports: any;
}

declare module 'react-use/lib/useNumber' {
  declare module.exports: any;
}

declare module 'react-use/lib/useObservable' {
  declare module.exports: any;
}

declare module 'react-use/lib/useOrientation' {
  declare module.exports: any;
}

declare module 'react-use/lib/usePageLeave' {
  declare module.exports: any;
}

declare module 'react-use/lib/usePermission' {
  declare module.exports: any;
}

declare module 'react-use/lib/usePinchZoom' {
  declare module.exports: any;
}

declare module 'react-use/lib/usePrevious' {
  declare module.exports: any;
}

declare module 'react-use/lib/usePreviousDistinct' {
  declare module.exports: any;
}

declare module 'react-use/lib/usePromise' {
  declare module.exports: any;
}

declare module 'react-use/lib/useQueue' {
  declare module.exports: any;
}

declare module 'react-use/lib/useRaf' {
  declare module.exports: any;
}

declare module 'react-use/lib/useRafLoop' {
  declare module.exports: any;
}

declare module 'react-use/lib/useRafState' {
  declare module.exports: any;
}

declare module 'react-use/lib/useRendersCount' {
  declare module.exports: any;
}

declare module 'react-use/lib/useScratch' {
  declare module.exports: any;
}

declare module 'react-use/lib/useScroll' {
  declare module.exports: any;
}

declare module 'react-use/lib/useScrollbarWidth' {
  declare module.exports: any;
}

declare module 'react-use/lib/useScrolling' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSearchParam' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSessionStorage' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSet' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSetState' {
  declare module.exports: any;
}

declare module 'react-use/lib/useShallowCompareEffect' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSize' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSlider' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSpeech' {
  declare module.exports: any;
}

declare module 'react-use/lib/useSpring' {
  declare module.exports: any;
}

declare module 'react-use/lib/useStartTyping' {
  declare module.exports: any;
}

declare module 'react-use/lib/useStateList' {
  declare module.exports: any;
}

declare module 'react-use/lib/useStateValidator' {
  declare module.exports: any;
}

declare module 'react-use/lib/useStateWithHistory' {
  declare module.exports: any;
}

declare module 'react-use/lib/useThrottle' {
  declare module.exports: any;
}

declare module 'react-use/lib/useThrottleFn' {
  declare module.exports: any;
}

declare module 'react-use/lib/useTimeout' {
  declare module.exports: any;
}

declare module 'react-use/lib/useTimeoutFn' {
  declare module.exports: any;
}

declare module 'react-use/lib/useTitle' {
  declare module.exports: any;
}

declare module 'react-use/lib/useToggle' {
  declare module.exports: any;
}

declare module 'react-use/lib/useTween' {
  declare module.exports: any;
}

declare module 'react-use/lib/useUnmount' {
  declare module.exports: any;
}

declare module 'react-use/lib/useUnmountPromise' {
  declare module.exports: any;
}

declare module 'react-use/lib/useUpdate' {
  declare module.exports: any;
}

declare module 'react-use/lib/useUpdateEffect' {
  declare module.exports: any;
}

declare module 'react-use/lib/useUpsert' {
  declare module.exports: any;
}

declare module 'react-use/lib/useVibrate' {
  declare module.exports: any;
}

declare module 'react-use/lib/useVideo' {
  declare module.exports: any;
}

declare module 'react-use/lib/useWait' {
  declare module.exports: any;
}

declare module 'react-use/lib/useWindowScroll' {
  declare module.exports: any;
}

declare module 'react-use/lib/useWindowSize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-use/esm/component/UseKey.js' {
  declare module.exports: $Exports<'react-use/esm/component/UseKey'>;
}
declare module 'react-use/esm/factory/createBreakpoint.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createBreakpoint'>;
}
declare module 'react-use/esm/factory/createGlobalState.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createGlobalState'>;
}
declare module 'react-use/esm/factory/createHTMLMediaHook.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createHTMLMediaHook'>;
}
declare module 'react-use/esm/factory/createMemo.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createMemo'>;
}
declare module 'react-use/esm/factory/createReducer.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createReducer'>;
}
declare module 'react-use/esm/factory/createReducerContext.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createReducerContext'>;
}
declare module 'react-use/esm/factory/createRenderProp.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createRenderProp'>;
}
declare module 'react-use/esm/factory/createRouter.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createRouter'>;
}
declare module 'react-use/esm/factory/createStateContext.js' {
  declare module.exports: $Exports<'react-use/esm/factory/createStateContext'>;
}
declare module 'react-use/esm/index' {
  declare module.exports: $Exports<'react-use/esm'>;
}
declare module 'react-use/esm/index.js' {
  declare module.exports: $Exports<'react-use/esm'>;
}
declare module 'react-use/esm/misc/hookState.js' {
  declare module.exports: $Exports<'react-use/esm/misc/hookState'>;
}
declare module 'react-use/esm/misc/isDeepEqual.js' {
  declare module.exports: $Exports<'react-use/esm/misc/isDeepEqual'>;
}
declare module 'react-use/esm/misc/parseTimeRanges.js' {
  declare module.exports: $Exports<'react-use/esm/misc/parseTimeRanges'>;
}
declare module 'react-use/esm/misc/types.js' {
  declare module.exports: $Exports<'react-use/esm/misc/types'>;
}
declare module 'react-use/esm/misc/util.js' {
  declare module.exports: $Exports<'react-use/esm/misc/util'>;
}
declare module 'react-use/esm/useAsync.js' {
  declare module.exports: $Exports<'react-use/esm/useAsync'>;
}
declare module 'react-use/esm/useAsyncFn.js' {
  declare module.exports: $Exports<'react-use/esm/useAsyncFn'>;
}
declare module 'react-use/esm/useAsyncRetry.js' {
  declare module.exports: $Exports<'react-use/esm/useAsyncRetry'>;
}
declare module 'react-use/esm/useAudio.js' {
  declare module.exports: $Exports<'react-use/esm/useAudio'>;
}
declare module 'react-use/esm/useBattery.js' {
  declare module.exports: $Exports<'react-use/esm/useBattery'>;
}
declare module 'react-use/esm/useBeforeUnload.js' {
  declare module.exports: $Exports<'react-use/esm/useBeforeUnload'>;
}
declare module 'react-use/esm/useBoolean.js' {
  declare module.exports: $Exports<'react-use/esm/useBoolean'>;
}
declare module 'react-use/esm/useClickAway.js' {
  declare module.exports: $Exports<'react-use/esm/useClickAway'>;
}
declare module 'react-use/esm/useCookie.js' {
  declare module.exports: $Exports<'react-use/esm/useCookie'>;
}
declare module 'react-use/esm/useCopyToClipboard.js' {
  declare module.exports: $Exports<'react-use/esm/useCopyToClipboard'>;
}
declare module 'react-use/esm/useCounter.js' {
  declare module.exports: $Exports<'react-use/esm/useCounter'>;
}
declare module 'react-use/esm/useCss.js' {
  declare module.exports: $Exports<'react-use/esm/useCss'>;
}
declare module 'react-use/esm/useCustomCompareEffect.js' {
  declare module.exports: $Exports<'react-use/esm/useCustomCompareEffect'>;
}
declare module 'react-use/esm/useDebounce.js' {
  declare module.exports: $Exports<'react-use/esm/useDebounce'>;
}
declare module 'react-use/esm/useDeepCompareEffect.js' {
  declare module.exports: $Exports<'react-use/esm/useDeepCompareEffect'>;
}
declare module 'react-use/esm/useDefault.js' {
  declare module.exports: $Exports<'react-use/esm/useDefault'>;
}
declare module 'react-use/esm/useDrop.js' {
  declare module.exports: $Exports<'react-use/esm/useDrop'>;
}
declare module 'react-use/esm/useDropArea.js' {
  declare module.exports: $Exports<'react-use/esm/useDropArea'>;
}
declare module 'react-use/esm/useEffectOnce.js' {
  declare module.exports: $Exports<'react-use/esm/useEffectOnce'>;
}
declare module 'react-use/esm/useEnsuredForwardedRef.js' {
  declare module.exports: $Exports<'react-use/esm/useEnsuredForwardedRef'>;
}
declare module 'react-use/esm/useError.js' {
  declare module.exports: $Exports<'react-use/esm/useError'>;
}
declare module 'react-use/esm/useEvent.js' {
  declare module.exports: $Exports<'react-use/esm/useEvent'>;
}
declare module 'react-use/esm/useFavicon.js' {
  declare module.exports: $Exports<'react-use/esm/useFavicon'>;
}
declare module 'react-use/esm/useFirstMountState.js' {
  declare module.exports: $Exports<'react-use/esm/useFirstMountState'>;
}
declare module 'react-use/esm/useFullscreen.js' {
  declare module.exports: $Exports<'react-use/esm/useFullscreen'>;
}
declare module 'react-use/esm/useGeolocation.js' {
  declare module.exports: $Exports<'react-use/esm/useGeolocation'>;
}
declare module 'react-use/esm/useGetSet.js' {
  declare module.exports: $Exports<'react-use/esm/useGetSet'>;
}
declare module 'react-use/esm/useGetSetState.js' {
  declare module.exports: $Exports<'react-use/esm/useGetSetState'>;
}
declare module 'react-use/esm/useHarmonicIntervalFn.js' {
  declare module.exports: $Exports<'react-use/esm/useHarmonicIntervalFn'>;
}
declare module 'react-use/esm/useHash.js' {
  declare module.exports: $Exports<'react-use/esm/useHash'>;
}
declare module 'react-use/esm/useHover.js' {
  declare module.exports: $Exports<'react-use/esm/useHover'>;
}
declare module 'react-use/esm/useHoverDirty.js' {
  declare module.exports: $Exports<'react-use/esm/useHoverDirty'>;
}
declare module 'react-use/esm/useIdle.js' {
  declare module.exports: $Exports<'react-use/esm/useIdle'>;
}
declare module 'react-use/esm/useIntersection.js' {
  declare module.exports: $Exports<'react-use/esm/useIntersection'>;
}
declare module 'react-use/esm/useInterval.js' {
  declare module.exports: $Exports<'react-use/esm/useInterval'>;
}
declare module 'react-use/esm/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-use/esm/useIsomorphicLayoutEffect'>;
}
declare module 'react-use/esm/useKey.js' {
  declare module.exports: $Exports<'react-use/esm/useKey'>;
}
declare module 'react-use/esm/useKeyboardJs.js' {
  declare module.exports: $Exports<'react-use/esm/useKeyboardJs'>;
}
declare module 'react-use/esm/useKeyPress.js' {
  declare module.exports: $Exports<'react-use/esm/useKeyPress'>;
}
declare module 'react-use/esm/useKeyPressEvent.js' {
  declare module.exports: $Exports<'react-use/esm/useKeyPressEvent'>;
}
declare module 'react-use/esm/useLatest.js' {
  declare module.exports: $Exports<'react-use/esm/useLatest'>;
}
declare module 'react-use/esm/useLifecycles.js' {
  declare module.exports: $Exports<'react-use/esm/useLifecycles'>;
}
declare module 'react-use/esm/useList.js' {
  declare module.exports: $Exports<'react-use/esm/useList'>;
}
declare module 'react-use/esm/useLocalStorage.js' {
  declare module.exports: $Exports<'react-use/esm/useLocalStorage'>;
}
declare module 'react-use/esm/useLocation.js' {
  declare module.exports: $Exports<'react-use/esm/useLocation'>;
}
declare module 'react-use/esm/useLockBodyScroll.js' {
  declare module.exports: $Exports<'react-use/esm/useLockBodyScroll'>;
}
declare module 'react-use/esm/useLogger.js' {
  declare module.exports: $Exports<'react-use/esm/useLogger'>;
}
declare module 'react-use/esm/useLongPress.js' {
  declare module.exports: $Exports<'react-use/esm/useLongPress'>;
}
declare module 'react-use/esm/useMap.js' {
  declare module.exports: $Exports<'react-use/esm/useMap'>;
}
declare module 'react-use/esm/useMeasure.js' {
  declare module.exports: $Exports<'react-use/esm/useMeasure'>;
}
declare module 'react-use/esm/useMeasureDirty.js' {
  declare module.exports: $Exports<'react-use/esm/useMeasureDirty'>;
}
declare module 'react-use/esm/useMedia.js' {
  declare module.exports: $Exports<'react-use/esm/useMedia'>;
}
declare module 'react-use/esm/useMediaDevices.js' {
  declare module.exports: $Exports<'react-use/esm/useMediaDevices'>;
}
declare module 'react-use/esm/useMediatedState.js' {
  declare module.exports: $Exports<'react-use/esm/useMediatedState'>;
}
declare module 'react-use/esm/useMethods.js' {
  declare module.exports: $Exports<'react-use/esm/useMethods'>;
}
declare module 'react-use/esm/useMotion.js' {
  declare module.exports: $Exports<'react-use/esm/useMotion'>;
}
declare module 'react-use/esm/useMount.js' {
  declare module.exports: $Exports<'react-use/esm/useMount'>;
}
declare module 'react-use/esm/useMountedState.js' {
  declare module.exports: $Exports<'react-use/esm/useMountedState'>;
}
declare module 'react-use/esm/useMouse.js' {
  declare module.exports: $Exports<'react-use/esm/useMouse'>;
}
declare module 'react-use/esm/useMouseHovered.js' {
  declare module.exports: $Exports<'react-use/esm/useMouseHovered'>;
}
declare module 'react-use/esm/useMouseWheel.js' {
  declare module.exports: $Exports<'react-use/esm/useMouseWheel'>;
}
declare module 'react-use/esm/useMultiStateValidator.js' {
  declare module.exports: $Exports<'react-use/esm/useMultiStateValidator'>;
}
declare module 'react-use/esm/useNetworkState.js' {
  declare module.exports: $Exports<'react-use/esm/useNetworkState'>;
}
declare module 'react-use/esm/useNumber.js' {
  declare module.exports: $Exports<'react-use/esm/useNumber'>;
}
declare module 'react-use/esm/useObservable.js' {
  declare module.exports: $Exports<'react-use/esm/useObservable'>;
}
declare module 'react-use/esm/useOrientation.js' {
  declare module.exports: $Exports<'react-use/esm/useOrientation'>;
}
declare module 'react-use/esm/usePageLeave.js' {
  declare module.exports: $Exports<'react-use/esm/usePageLeave'>;
}
declare module 'react-use/esm/usePermission.js' {
  declare module.exports: $Exports<'react-use/esm/usePermission'>;
}
declare module 'react-use/esm/usePinchZoom.js' {
  declare module.exports: $Exports<'react-use/esm/usePinchZoom'>;
}
declare module 'react-use/esm/usePrevious.js' {
  declare module.exports: $Exports<'react-use/esm/usePrevious'>;
}
declare module 'react-use/esm/usePreviousDistinct.js' {
  declare module.exports: $Exports<'react-use/esm/usePreviousDistinct'>;
}
declare module 'react-use/esm/usePromise.js' {
  declare module.exports: $Exports<'react-use/esm/usePromise'>;
}
declare module 'react-use/esm/useQueue.js' {
  declare module.exports: $Exports<'react-use/esm/useQueue'>;
}
declare module 'react-use/esm/useRaf.js' {
  declare module.exports: $Exports<'react-use/esm/useRaf'>;
}
declare module 'react-use/esm/useRafLoop.js' {
  declare module.exports: $Exports<'react-use/esm/useRafLoop'>;
}
declare module 'react-use/esm/useRafState.js' {
  declare module.exports: $Exports<'react-use/esm/useRafState'>;
}
declare module 'react-use/esm/useRendersCount.js' {
  declare module.exports: $Exports<'react-use/esm/useRendersCount'>;
}
declare module 'react-use/esm/useScratch.js' {
  declare module.exports: $Exports<'react-use/esm/useScratch'>;
}
declare module 'react-use/esm/useScroll.js' {
  declare module.exports: $Exports<'react-use/esm/useScroll'>;
}
declare module 'react-use/esm/useScrollbarWidth.js' {
  declare module.exports: $Exports<'react-use/esm/useScrollbarWidth'>;
}
declare module 'react-use/esm/useScrolling.js' {
  declare module.exports: $Exports<'react-use/esm/useScrolling'>;
}
declare module 'react-use/esm/useSearchParam.js' {
  declare module.exports: $Exports<'react-use/esm/useSearchParam'>;
}
declare module 'react-use/esm/useSessionStorage.js' {
  declare module.exports: $Exports<'react-use/esm/useSessionStorage'>;
}
declare module 'react-use/esm/useSet.js' {
  declare module.exports: $Exports<'react-use/esm/useSet'>;
}
declare module 'react-use/esm/useSetState.js' {
  declare module.exports: $Exports<'react-use/esm/useSetState'>;
}
declare module 'react-use/esm/useShallowCompareEffect.js' {
  declare module.exports: $Exports<'react-use/esm/useShallowCompareEffect'>;
}
declare module 'react-use/esm/useSize.js' {
  declare module.exports: $Exports<'react-use/esm/useSize'>;
}
declare module 'react-use/esm/useSlider.js' {
  declare module.exports: $Exports<'react-use/esm/useSlider'>;
}
declare module 'react-use/esm/useSpeech.js' {
  declare module.exports: $Exports<'react-use/esm/useSpeech'>;
}
declare module 'react-use/esm/useSpring.js' {
  declare module.exports: $Exports<'react-use/esm/useSpring'>;
}
declare module 'react-use/esm/useStartTyping.js' {
  declare module.exports: $Exports<'react-use/esm/useStartTyping'>;
}
declare module 'react-use/esm/useStateList.js' {
  declare module.exports: $Exports<'react-use/esm/useStateList'>;
}
declare module 'react-use/esm/useStateValidator.js' {
  declare module.exports: $Exports<'react-use/esm/useStateValidator'>;
}
declare module 'react-use/esm/useStateWithHistory.js' {
  declare module.exports: $Exports<'react-use/esm/useStateWithHistory'>;
}
declare module 'react-use/esm/useThrottle.js' {
  declare module.exports: $Exports<'react-use/esm/useThrottle'>;
}
declare module 'react-use/esm/useThrottleFn.js' {
  declare module.exports: $Exports<'react-use/esm/useThrottleFn'>;
}
declare module 'react-use/esm/useTimeout.js' {
  declare module.exports: $Exports<'react-use/esm/useTimeout'>;
}
declare module 'react-use/esm/useTimeoutFn.js' {
  declare module.exports: $Exports<'react-use/esm/useTimeoutFn'>;
}
declare module 'react-use/esm/useTitle.js' {
  declare module.exports: $Exports<'react-use/esm/useTitle'>;
}
declare module 'react-use/esm/useToggle.js' {
  declare module.exports: $Exports<'react-use/esm/useToggle'>;
}
declare module 'react-use/esm/useTween.js' {
  declare module.exports: $Exports<'react-use/esm/useTween'>;
}
declare module 'react-use/esm/useUnmount.js' {
  declare module.exports: $Exports<'react-use/esm/useUnmount'>;
}
declare module 'react-use/esm/useUnmountPromise.js' {
  declare module.exports: $Exports<'react-use/esm/useUnmountPromise'>;
}
declare module 'react-use/esm/useUpdate.js' {
  declare module.exports: $Exports<'react-use/esm/useUpdate'>;
}
declare module 'react-use/esm/useUpdateEffect.js' {
  declare module.exports: $Exports<'react-use/esm/useUpdateEffect'>;
}
declare module 'react-use/esm/useUpsert.js' {
  declare module.exports: $Exports<'react-use/esm/useUpsert'>;
}
declare module 'react-use/esm/useVibrate.js' {
  declare module.exports: $Exports<'react-use/esm/useVibrate'>;
}
declare module 'react-use/esm/useVideo.js' {
  declare module.exports: $Exports<'react-use/esm/useVideo'>;
}
declare module 'react-use/esm/useWait.js' {
  declare module.exports: $Exports<'react-use/esm/useWait'>;
}
declare module 'react-use/esm/useWindowScroll.js' {
  declare module.exports: $Exports<'react-use/esm/useWindowScroll'>;
}
declare module 'react-use/esm/useWindowSize.js' {
  declare module.exports: $Exports<'react-use/esm/useWindowSize'>;
}
declare module 'react-use/lib/component/UseKey.js' {
  declare module.exports: $Exports<'react-use/lib/component/UseKey'>;
}
declare module 'react-use/lib/factory/createBreakpoint.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createBreakpoint'>;
}
declare module 'react-use/lib/factory/createGlobalState.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createGlobalState'>;
}
declare module 'react-use/lib/factory/createHTMLMediaHook.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createHTMLMediaHook'>;
}
declare module 'react-use/lib/factory/createMemo.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createMemo'>;
}
declare module 'react-use/lib/factory/createReducer.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createReducer'>;
}
declare module 'react-use/lib/factory/createReducerContext.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createReducerContext'>;
}
declare module 'react-use/lib/factory/createRenderProp.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createRenderProp'>;
}
declare module 'react-use/lib/factory/createRouter.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createRouter'>;
}
declare module 'react-use/lib/factory/createStateContext.js' {
  declare module.exports: $Exports<'react-use/lib/factory/createStateContext'>;
}
declare module 'react-use/lib/index' {
  declare module.exports: $Exports<'react-use/lib'>;
}
declare module 'react-use/lib/index.js' {
  declare module.exports: $Exports<'react-use/lib'>;
}
declare module 'react-use/lib/misc/hookState.js' {
  declare module.exports: $Exports<'react-use/lib/misc/hookState'>;
}
declare module 'react-use/lib/misc/isDeepEqual.js' {
  declare module.exports: $Exports<'react-use/lib/misc/isDeepEqual'>;
}
declare module 'react-use/lib/misc/parseTimeRanges.js' {
  declare module.exports: $Exports<'react-use/lib/misc/parseTimeRanges'>;
}
declare module 'react-use/lib/misc/types.js' {
  declare module.exports: $Exports<'react-use/lib/misc/types'>;
}
declare module 'react-use/lib/misc/util.js' {
  declare module.exports: $Exports<'react-use/lib/misc/util'>;
}
declare module 'react-use/lib/useAsync.js' {
  declare module.exports: $Exports<'react-use/lib/useAsync'>;
}
declare module 'react-use/lib/useAsyncFn.js' {
  declare module.exports: $Exports<'react-use/lib/useAsyncFn'>;
}
declare module 'react-use/lib/useAsyncRetry.js' {
  declare module.exports: $Exports<'react-use/lib/useAsyncRetry'>;
}
declare module 'react-use/lib/useAudio.js' {
  declare module.exports: $Exports<'react-use/lib/useAudio'>;
}
declare module 'react-use/lib/useBattery.js' {
  declare module.exports: $Exports<'react-use/lib/useBattery'>;
}
declare module 'react-use/lib/useBeforeUnload.js' {
  declare module.exports: $Exports<'react-use/lib/useBeforeUnload'>;
}
declare module 'react-use/lib/useBoolean.js' {
  declare module.exports: $Exports<'react-use/lib/useBoolean'>;
}
declare module 'react-use/lib/useClickAway.js' {
  declare module.exports: $Exports<'react-use/lib/useClickAway'>;
}
declare module 'react-use/lib/useCookie.js' {
  declare module.exports: $Exports<'react-use/lib/useCookie'>;
}
declare module 'react-use/lib/useCopyToClipboard.js' {
  declare module.exports: $Exports<'react-use/lib/useCopyToClipboard'>;
}
declare module 'react-use/lib/useCounter.js' {
  declare module.exports: $Exports<'react-use/lib/useCounter'>;
}
declare module 'react-use/lib/useCss.js' {
  declare module.exports: $Exports<'react-use/lib/useCss'>;
}
declare module 'react-use/lib/useCustomCompareEffect.js' {
  declare module.exports: $Exports<'react-use/lib/useCustomCompareEffect'>;
}
declare module 'react-use/lib/useDebounce.js' {
  declare module.exports: $Exports<'react-use/lib/useDebounce'>;
}
declare module 'react-use/lib/useDeepCompareEffect.js' {
  declare module.exports: $Exports<'react-use/lib/useDeepCompareEffect'>;
}
declare module 'react-use/lib/useDefault.js' {
  declare module.exports: $Exports<'react-use/lib/useDefault'>;
}
declare module 'react-use/lib/useDrop.js' {
  declare module.exports: $Exports<'react-use/lib/useDrop'>;
}
declare module 'react-use/lib/useDropArea.js' {
  declare module.exports: $Exports<'react-use/lib/useDropArea'>;
}
declare module 'react-use/lib/useEffectOnce.js' {
  declare module.exports: $Exports<'react-use/lib/useEffectOnce'>;
}
declare module 'react-use/lib/useEnsuredForwardedRef.js' {
  declare module.exports: $Exports<'react-use/lib/useEnsuredForwardedRef'>;
}
declare module 'react-use/lib/useError.js' {
  declare module.exports: $Exports<'react-use/lib/useError'>;
}
declare module 'react-use/lib/useEvent.js' {
  declare module.exports: $Exports<'react-use/lib/useEvent'>;
}
declare module 'react-use/lib/useFavicon.js' {
  declare module.exports: $Exports<'react-use/lib/useFavicon'>;
}
declare module 'react-use/lib/useFirstMountState.js' {
  declare module.exports: $Exports<'react-use/lib/useFirstMountState'>;
}
declare module 'react-use/lib/useFullscreen.js' {
  declare module.exports: $Exports<'react-use/lib/useFullscreen'>;
}
declare module 'react-use/lib/useGeolocation.js' {
  declare module.exports: $Exports<'react-use/lib/useGeolocation'>;
}
declare module 'react-use/lib/useGetSet.js' {
  declare module.exports: $Exports<'react-use/lib/useGetSet'>;
}
declare module 'react-use/lib/useGetSetState.js' {
  declare module.exports: $Exports<'react-use/lib/useGetSetState'>;
}
declare module 'react-use/lib/useHarmonicIntervalFn.js' {
  declare module.exports: $Exports<'react-use/lib/useHarmonicIntervalFn'>;
}
declare module 'react-use/lib/useHash.js' {
  declare module.exports: $Exports<'react-use/lib/useHash'>;
}
declare module 'react-use/lib/useHover.js' {
  declare module.exports: $Exports<'react-use/lib/useHover'>;
}
declare module 'react-use/lib/useHoverDirty.js' {
  declare module.exports: $Exports<'react-use/lib/useHoverDirty'>;
}
declare module 'react-use/lib/useIdle.js' {
  declare module.exports: $Exports<'react-use/lib/useIdle'>;
}
declare module 'react-use/lib/useIntersection.js' {
  declare module.exports: $Exports<'react-use/lib/useIntersection'>;
}
declare module 'react-use/lib/useInterval.js' {
  declare module.exports: $Exports<'react-use/lib/useInterval'>;
}
declare module 'react-use/lib/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-use/lib/useIsomorphicLayoutEffect'>;
}
declare module 'react-use/lib/useKey.js' {
  declare module.exports: $Exports<'react-use/lib/useKey'>;
}
declare module 'react-use/lib/useKeyboardJs.js' {
  declare module.exports: $Exports<'react-use/lib/useKeyboardJs'>;
}
declare module 'react-use/lib/useKeyPress.js' {
  declare module.exports: $Exports<'react-use/lib/useKeyPress'>;
}
declare module 'react-use/lib/useKeyPressEvent.js' {
  declare module.exports: $Exports<'react-use/lib/useKeyPressEvent'>;
}
declare module 'react-use/lib/useLatest.js' {
  declare module.exports: $Exports<'react-use/lib/useLatest'>;
}
declare module 'react-use/lib/useLifecycles.js' {
  declare module.exports: $Exports<'react-use/lib/useLifecycles'>;
}
declare module 'react-use/lib/useList.js' {
  declare module.exports: $Exports<'react-use/lib/useList'>;
}
declare module 'react-use/lib/useLocalStorage.js' {
  declare module.exports: $Exports<'react-use/lib/useLocalStorage'>;
}
declare module 'react-use/lib/useLocation.js' {
  declare module.exports: $Exports<'react-use/lib/useLocation'>;
}
declare module 'react-use/lib/useLockBodyScroll.js' {
  declare module.exports: $Exports<'react-use/lib/useLockBodyScroll'>;
}
declare module 'react-use/lib/useLogger.js' {
  declare module.exports: $Exports<'react-use/lib/useLogger'>;
}
declare module 'react-use/lib/useLongPress.js' {
  declare module.exports: $Exports<'react-use/lib/useLongPress'>;
}
declare module 'react-use/lib/useMap.js' {
  declare module.exports: $Exports<'react-use/lib/useMap'>;
}
declare module 'react-use/lib/useMeasure.js' {
  declare module.exports: $Exports<'react-use/lib/useMeasure'>;
}
declare module 'react-use/lib/useMeasureDirty.js' {
  declare module.exports: $Exports<'react-use/lib/useMeasureDirty'>;
}
declare module 'react-use/lib/useMedia.js' {
  declare module.exports: $Exports<'react-use/lib/useMedia'>;
}
declare module 'react-use/lib/useMediaDevices.js' {
  declare module.exports: $Exports<'react-use/lib/useMediaDevices'>;
}
declare module 'react-use/lib/useMediatedState.js' {
  declare module.exports: $Exports<'react-use/lib/useMediatedState'>;
}
declare module 'react-use/lib/useMethods.js' {
  declare module.exports: $Exports<'react-use/lib/useMethods'>;
}
declare module 'react-use/lib/useMotion.js' {
  declare module.exports: $Exports<'react-use/lib/useMotion'>;
}
declare module 'react-use/lib/useMount.js' {
  declare module.exports: $Exports<'react-use/lib/useMount'>;
}
declare module 'react-use/lib/useMountedState.js' {
  declare module.exports: $Exports<'react-use/lib/useMountedState'>;
}
declare module 'react-use/lib/useMouse.js' {
  declare module.exports: $Exports<'react-use/lib/useMouse'>;
}
declare module 'react-use/lib/useMouseHovered.js' {
  declare module.exports: $Exports<'react-use/lib/useMouseHovered'>;
}
declare module 'react-use/lib/useMouseWheel.js' {
  declare module.exports: $Exports<'react-use/lib/useMouseWheel'>;
}
declare module 'react-use/lib/useMultiStateValidator.js' {
  declare module.exports: $Exports<'react-use/lib/useMultiStateValidator'>;
}
declare module 'react-use/lib/useNetworkState.js' {
  declare module.exports: $Exports<'react-use/lib/useNetworkState'>;
}
declare module 'react-use/lib/useNumber.js' {
  declare module.exports: $Exports<'react-use/lib/useNumber'>;
}
declare module 'react-use/lib/useObservable.js' {
  declare module.exports: $Exports<'react-use/lib/useObservable'>;
}
declare module 'react-use/lib/useOrientation.js' {
  declare module.exports: $Exports<'react-use/lib/useOrientation'>;
}
declare module 'react-use/lib/usePageLeave.js' {
  declare module.exports: $Exports<'react-use/lib/usePageLeave'>;
}
declare module 'react-use/lib/usePermission.js' {
  declare module.exports: $Exports<'react-use/lib/usePermission'>;
}
declare module 'react-use/lib/usePinchZoom.js' {
  declare module.exports: $Exports<'react-use/lib/usePinchZoom'>;
}
declare module 'react-use/lib/usePrevious.js' {
  declare module.exports: $Exports<'react-use/lib/usePrevious'>;
}
declare module 'react-use/lib/usePreviousDistinct.js' {
  declare module.exports: $Exports<'react-use/lib/usePreviousDistinct'>;
}
declare module 'react-use/lib/usePromise.js' {
  declare module.exports: $Exports<'react-use/lib/usePromise'>;
}
declare module 'react-use/lib/useQueue.js' {
  declare module.exports: $Exports<'react-use/lib/useQueue'>;
}
declare module 'react-use/lib/useRaf.js' {
  declare module.exports: $Exports<'react-use/lib/useRaf'>;
}
declare module 'react-use/lib/useRafLoop.js' {
  declare module.exports: $Exports<'react-use/lib/useRafLoop'>;
}
declare module 'react-use/lib/useRafState.js' {
  declare module.exports: $Exports<'react-use/lib/useRafState'>;
}
declare module 'react-use/lib/useRendersCount.js' {
  declare module.exports: $Exports<'react-use/lib/useRendersCount'>;
}
declare module 'react-use/lib/useScratch.js' {
  declare module.exports: $Exports<'react-use/lib/useScratch'>;
}
declare module 'react-use/lib/useScroll.js' {
  declare module.exports: $Exports<'react-use/lib/useScroll'>;
}
declare module 'react-use/lib/useScrollbarWidth.js' {
  declare module.exports: $Exports<'react-use/lib/useScrollbarWidth'>;
}
declare module 'react-use/lib/useScrolling.js' {
  declare module.exports: $Exports<'react-use/lib/useScrolling'>;
}
declare module 'react-use/lib/useSearchParam.js' {
  declare module.exports: $Exports<'react-use/lib/useSearchParam'>;
}
declare module 'react-use/lib/useSessionStorage.js' {
  declare module.exports: $Exports<'react-use/lib/useSessionStorage'>;
}
declare module 'react-use/lib/useSet.js' {
  declare module.exports: $Exports<'react-use/lib/useSet'>;
}
declare module 'react-use/lib/useSetState.js' {
  declare module.exports: $Exports<'react-use/lib/useSetState'>;
}
declare module 'react-use/lib/useShallowCompareEffect.js' {
  declare module.exports: $Exports<'react-use/lib/useShallowCompareEffect'>;
}
declare module 'react-use/lib/useSize.js' {
  declare module.exports: $Exports<'react-use/lib/useSize'>;
}
declare module 'react-use/lib/useSlider.js' {
  declare module.exports: $Exports<'react-use/lib/useSlider'>;
}
declare module 'react-use/lib/useSpeech.js' {
  declare module.exports: $Exports<'react-use/lib/useSpeech'>;
}
declare module 'react-use/lib/useSpring.js' {
  declare module.exports: $Exports<'react-use/lib/useSpring'>;
}
declare module 'react-use/lib/useStartTyping.js' {
  declare module.exports: $Exports<'react-use/lib/useStartTyping'>;
}
declare module 'react-use/lib/useStateList.js' {
  declare module.exports: $Exports<'react-use/lib/useStateList'>;
}
declare module 'react-use/lib/useStateValidator.js' {
  declare module.exports: $Exports<'react-use/lib/useStateValidator'>;
}
declare module 'react-use/lib/useStateWithHistory.js' {
  declare module.exports: $Exports<'react-use/lib/useStateWithHistory'>;
}
declare module 'react-use/lib/useThrottle.js' {
  declare module.exports: $Exports<'react-use/lib/useThrottle'>;
}
declare module 'react-use/lib/useThrottleFn.js' {
  declare module.exports: $Exports<'react-use/lib/useThrottleFn'>;
}
declare module 'react-use/lib/useTimeout.js' {
  declare module.exports: $Exports<'react-use/lib/useTimeout'>;
}
declare module 'react-use/lib/useTimeoutFn.js' {
  declare module.exports: $Exports<'react-use/lib/useTimeoutFn'>;
}
declare module 'react-use/lib/useTitle.js' {
  declare module.exports: $Exports<'react-use/lib/useTitle'>;
}
declare module 'react-use/lib/useToggle.js' {
  declare module.exports: $Exports<'react-use/lib/useToggle'>;
}
declare module 'react-use/lib/useTween.js' {
  declare module.exports: $Exports<'react-use/lib/useTween'>;
}
declare module 'react-use/lib/useUnmount.js' {
  declare module.exports: $Exports<'react-use/lib/useUnmount'>;
}
declare module 'react-use/lib/useUnmountPromise.js' {
  declare module.exports: $Exports<'react-use/lib/useUnmountPromise'>;
}
declare module 'react-use/lib/useUpdate.js' {
  declare module.exports: $Exports<'react-use/lib/useUpdate'>;
}
declare module 'react-use/lib/useUpdateEffect.js' {
  declare module.exports: $Exports<'react-use/lib/useUpdateEffect'>;
}
declare module 'react-use/lib/useUpsert.js' {
  declare module.exports: $Exports<'react-use/lib/useUpsert'>;
}
declare module 'react-use/lib/useVibrate.js' {
  declare module.exports: $Exports<'react-use/lib/useVibrate'>;
}
declare module 'react-use/lib/useVideo.js' {
  declare module.exports: $Exports<'react-use/lib/useVideo'>;
}
declare module 'react-use/lib/useWait.js' {
  declare module.exports: $Exports<'react-use/lib/useWait'>;
}
declare module 'react-use/lib/useWindowScroll.js' {
  declare module.exports: $Exports<'react-use/lib/useWindowScroll'>;
}
declare module 'react-use/lib/useWindowSize.js' {
  declare module.exports: $Exports<'react-use/lib/useWindowSize'>;
}
