// flow-typed signature: 8da8024438367e5e4b3d9efd601b193e
// flow-typed version: <<STUB>>/react_v19.2.3/flow_v0.231.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react/cjs/react-compiler-runtime.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react-compiler-runtime.production' {
  declare module.exports: any;
}

declare module 'react/cjs/react-compiler-runtime.profiling' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-dev-runtime.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-dev-runtime.production' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-dev-runtime.profiling' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-dev-runtime.react-server.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-dev-runtime.react-server.production' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-runtime.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-runtime.production' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-runtime.profiling' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-runtime.react-server.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react-jsx-runtime.react-server.production' {
  declare module.exports: any;
}

declare module 'react/cjs/react.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react.production' {
  declare module.exports: any;
}

declare module 'react/cjs/react.react-server.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react.react-server.production' {
  declare module.exports: any;
}

declare module 'react/compiler-runtime' {
  declare module.exports: any;
}

declare module 'react/jsx-dev-runtime' {
  declare module.exports: any;
}

declare module 'react/jsx-dev-runtime.react-server' {
  declare module.exports: any;
}

declare module 'react/jsx-runtime' {
  declare module.exports: any;
}

declare module 'react/jsx-runtime.react-server' {
  declare module.exports: any;
}

declare module 'react/react.react-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react/cjs/react-compiler-runtime.development.js' {
  declare module.exports: $Exports<'react/cjs/react-compiler-runtime.development'>;
}
declare module 'react/cjs/react-compiler-runtime.production.js' {
  declare module.exports: $Exports<'react/cjs/react-compiler-runtime.production'>;
}
declare module 'react/cjs/react-compiler-runtime.profiling.js' {
  declare module.exports: $Exports<'react/cjs/react-compiler-runtime.profiling'>;
}
declare module 'react/cjs/react-jsx-dev-runtime.development.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-dev-runtime.development'>;
}
declare module 'react/cjs/react-jsx-dev-runtime.production.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-dev-runtime.production'>;
}
declare module 'react/cjs/react-jsx-dev-runtime.profiling.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-dev-runtime.profiling'>;
}
declare module 'react/cjs/react-jsx-dev-runtime.react-server.development.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-dev-runtime.react-server.development'>;
}
declare module 'react/cjs/react-jsx-dev-runtime.react-server.production.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-dev-runtime.react-server.production'>;
}
declare module 'react/cjs/react-jsx-runtime.development.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-runtime.development'>;
}
declare module 'react/cjs/react-jsx-runtime.production.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-runtime.production'>;
}
declare module 'react/cjs/react-jsx-runtime.profiling.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-runtime.profiling'>;
}
declare module 'react/cjs/react-jsx-runtime.react-server.development.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-runtime.react-server.development'>;
}
declare module 'react/cjs/react-jsx-runtime.react-server.production.js' {
  declare module.exports: $Exports<'react/cjs/react-jsx-runtime.react-server.production'>;
}
declare module 'react/cjs/react.development.js' {
  declare module.exports: $Exports<'react/cjs/react.development'>;
}
declare module 'react/cjs/react.production.js' {
  declare module.exports: $Exports<'react/cjs/react.production'>;
}
declare module 'react/cjs/react.react-server.development.js' {
  declare module.exports: $Exports<'react/cjs/react.react-server.development'>;
}
declare module 'react/cjs/react.react-server.production.js' {
  declare module.exports: $Exports<'react/cjs/react.react-server.production'>;
}
declare module 'react/compiler-runtime.js' {
  declare module.exports: $Exports<'react/compiler-runtime'>;
}
declare module 'react/index' {
  declare module.exports: $Exports<'react'>;
}
declare module 'react/index.js' {
  declare module.exports: $Exports<'react'>;
}
declare module 'react/jsx-dev-runtime.js' {
  declare module.exports: $Exports<'react/jsx-dev-runtime'>;
}
declare module 'react/jsx-dev-runtime.react-server.js' {
  declare module.exports: $Exports<'react/jsx-dev-runtime.react-server'>;
}
declare module 'react/jsx-runtime.js' {
  declare module.exports: $Exports<'react/jsx-runtime'>;
}
declare module 'react/jsx-runtime.react-server.js' {
  declare module.exports: $Exports<'react/jsx-runtime.react-server'>;
}
declare module 'react/react.react-server.js' {
  declare module.exports: $Exports<'react/react.react-server'>;
}
